### ISSUE TITLE
trying to install into node-red - get the following error

### ISSUE THREAD

**Issue by herbsims** [meshtastic/node-red-contrib-meshtastic#5] opened 2023-02-28 15:23 UTC
[@meshtastic/node-red-contrib-meshtastic/decode] Error: Cannot find module '/home/test/.node-red/node_modules/@meshtastic/node-red-contrib-meshtastic/dist/cjs/decode.js'
Require stack:
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

**Comment by sachaw** [comment] 2023-12-10 02:22
@scruplelesswizard No longer persists?

**Comment by scruplelesswizard** [comment] 2023-12-11 17:33
This error would be caused by Node-Red's internal modules missing. This can be resolved by adding the [`node-red`](https://www.npmjs.com/package/node-red) module through the _Manage Pallette_ menu in the UI or by running `npm install --global node-red`
Please see the [Node-Red documentation](https://www.npmjs.com/package/node-red) for more details

**Comment by scruplelesswizard** [comment] 2024-01-12 23:49
> @scruplelesswizard No longer persists?

This is related missing the core Node-RED modules, nothing to do with Meshtastic. It can be closed

**Closed as not planned** 2024-01-18 05:20 UTC
